print("Hissssss....")
print("Zzsaaa!")
print("Hello, there is , someone , here?")
print("hello\nanybody home?")
print("the counter","top","is dirty")
print("can i make a meal", end="")
print("here?")
print("i will clean", end="\n")
print("this")
print("though", "when", "shall", "i", "eat", sep="-")
print("this will", "have to do", "i suppose", sep=", ", end="*\n")
print("tring" * 5)
print('"oh they\'s timing"')
print("3")
print(5)
